config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home", page: "home"
  get "/static_pages/:page", to: "static_pages#show"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/orders/completed", to: "orders#completed"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/aliexpress", to: "products#aliexpress"
  resources :products
  resources :users do
    member do
      get :products
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :order_lines
  resource :cart, only: [:show]
  resources :orders
  resources :relationships
  namespace :is_admin do
    resources :products
    resources :categories, except: [:edit, :update, :destroy]
    resources :orders
  end
  namespace :shipper do
    resources :orders
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin

  def index
    @categories = Category.select(:id, :parents_id,
      :name).order(:id).paginate page: params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Add Done"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by id: params[:id]
    if @category
      @books = @category.products.select(:id, :category_id, :name, :price,
        :quantity, :picture).paginate page: params[:page]
    else
      flash[:danger] = "Not Found"
      redirect_to root_path
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :parents_id
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    if logged_in?
      @order_line = current_order.order_lines.new
    end
  end

  def show
    if logged_in?
      @order_line = current_order.order_lines.new
    end
    @category = Category.find_by id: params[:id]
    if @category
      @products = @category.products.select(:id, :category_id, :name, :price,
        :quantity, :picture, :img_url).paginate page: params[:page]
    else
      flash[:danger] = "not found"
      redirect_to root_path
    end
  end
end

app/controllers/is_admin/categories_controller.rb
class IsAdmin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin

  def index
    @categories = Category.select(:id, :parents_id,
      :name).order(:id).paginate page: params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Add Done"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by id: params[:id]
    if @category
      @books = @category.products.select(:id, :category_id, :name, :price,
        :quantity, :picture).paginate page: params[:page]
    else
      flash[:danger] = "Not Found"
      redirect_to root_path
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :parents_id
  end
end

app/controllers/is_admin/orders_controller.rb
class IsAdmin::OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin
  
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find params[:id]
    @order_lines = @order.order_lines
  end

  def update
    @order = Order.find_by id: params[:id]
    if @order.update_attributes order_params
      flash[:success] = "Accept"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = "Can't Accept"
      redirect_to root_path
    end
  end

  private 

  def order_params
    params.require(:order).permit :state_order_id
  end
end

app/controllers/is_admin/products_controller.rb
class IsAdmin::ProductsController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin

  def index
    @products = Product.select(:id, :name, :quantity).order(:name).paginate page: params[:page]
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = "Add Done!"
      redirect_to @product
    else
      flash[:alert] = "Wrong"
      render :new
    end
  end

  def show
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:danger] = "Not found to show"
      redirect_to root_path
    end
  end

  def update
    @product = Product.find_by id: params[:id]
    if @product.update_attributes product_params
      flash[:success] = "Updated"
      redirect_to admin_product_path
    else
      render "edit"
    end
  end

  def edit
    @product = Product.find_by id: params[:id]
  end

  private

  def product_params
    params.require(:product).permit :name, :category_id, 
      :price, :description, :quantity , :picture
  end

end

app/views/is_admin/categories/index.html.erb
<% provide :title, "Category" %>
<div class="container">
  <br><h1><%= "Category" %></h1>
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <hr>
    <div class="panel panel-white post panel-shadow">
      <div class="post-footer">
        <ul class="comments-list">
          <li class="comment">
            <div class="comment-body">
              <h2 class="user"><%= link_to category.name, admin_category_path(category) %></h2>
            </div>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
  <%= will_paginate %>
</div>

app/views/is_admin/categories/new.html.erb
<% provide :title, "Category" %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
      <%= form_for [:admin, @category] do |f| %>
        <br><br><hr>
        <h2><%= "new" %></h2>
        <br>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg",
          placeholder: "name" %>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-6"><%= f.submit "add",
            class: "btn btn-warning btn-block btn-lg" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/is_admin/categories/show.html.erb
<div class="container">
  <div class="span3 well">
    <center>
      <h1><%= @category.name %></h2>
      <h3><%= t ".id" %><%= @category.id %></h3>
    </center>
  </div>
  <%= will_paginate @products %>
  <ul>
    <% @products.each do |product| %>
    <div class="panel panel-white post panel-shadow">
      <div class="post-footer">
        <ul class="comments-list">
          <li class="comment">
            <div class="row-fluid">
            <div class="span5">
              <div class="picture-list">
                <a>
                  <% if product.picture? %>
                    <center>
                      <br>
                      <%= image_tag(product.picture.url,
                        height: Settings.height_picture_product_index) %>
                    </center>
                  <% end %>
                </a>
              </div>
            </div>
            <div class="span7">
              <h3><%= link_to product.name, product %></h3>
              <hr class="soft"/>
              <div class="control-group">
                <h2><%= number_to_currency product.price %></h2>
                <br>
              </div>
              <h4><%= product.quantity %><%= "items stock" %></h4>
            </div>
          </div>
          </li>
        </ul>
      </div>
    </div>
    <hr class="colorgrap">
    <% end %>
  </ul>
  <%= will_paginate @products %>
</div>