config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home", page: "home"
  get "/static_pages/:page", to: "static_pages#show"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/orders/completed", to: "orders#completed"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/aliexpress", to: "products#aliexpress"
  resources :products
  resources :users do
    member do
      get :products
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :order_lines
  resource :cart, only: [:show]
  resources :orders
  resources :relationships
  namespace :is_admin do
    resources :products
    resources :categories, except: [:edit, :update, :destroy]
    resources :orders
  end
  namespace :shipper do
    resources :orders
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def new
    @cart = current_cart
    if @cart.cart_items.empty?
      flash[:danger] = 'Your cart is empty'
      redirect_to root_path
      return
    end
    @order = Order.new
  end

  def show
    if current_order
      @order_lines = current_order.order_lines
    else
      redirect_to root_path
    end
  end
end

app/views/carts/_cart_row.html.erb
<tr class="ahihihi">
   <%= form_for order_line, remote: true do |f| %>
   <td class="product-remove">
      <%= link_to "Delete", order_line, 
      {data: {confirm: "Confirm", name: order_line.product.name}, 
      method: :delete, remote: true, class: "btn btn-danger btn"} %>
      <!-- <a href="#" class="remove"><i class="fa fa-times-circle"></i></a> -->
   </td>
   <td class="product-img clearfix">
      <a href="single-product.html">
         <img src="images/collections/<%= product.id %>.jpg" alt="" class="product-image-photo">
      </a>
   </td>
   <td class="product-name-ct">
      <a href="single-product.html">
         <%= product.name %>
      </a>
   </td>
   <td class="product-price">
      <p class="price"><%= number_to_currency order_line.price %></p>
   </td>
   <td>
      <div class="quantity">
         <%= f.number_field :number, value: order_line.number.to_i, 
         class: "qty", min: 1 %>
      </div>
   </td>
   <td>
      <%= f.hidden_field :product_id, value: product.id %>
      <%= f.submit "Update Quantity", class: "btn btn-primary" %>
   </td>
   <td class="product-subtotal">
      <%= number_to_currency order_line.total_price %>
   </td>
   <% end %>
</tr> 

app/views/carts/_cart_shopping.html.erb
<% if @order_lines.size == 0 %>
<p class="text-center">
   There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
</p>
<% else %>
 <% @order_lines.each do |order_line| %>
    <%= render 'carts/cart_row', product: order_line.product, order_line: order_line, show_total: true %>
 <% end %>
<% end %>

app/views/carts/_shopping_cart.html.erb
<% provide :title, "Cart" %>
<% if !@order_line.nil? && @order_line.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @order_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if @order_lines.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_lines.each do |order_line| %>
    <%= render 'carts/cart_row', product: order_line.product, order_line: order_line, show_total: true %>
  <% end %>
<% end %>
<div class="container">
  <table id="cart" class="table table-hover table-condensed">
      <tr>
        <td><%= link_to "Continue Shopping", products_path, class: "btn btn-warning" %>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>Total Price: <%= number_to_currency current_order.subtotal %></strong></td>
        <td>
          <%= link_to "Checkout", new_order_path, class: "btn btn-success btn-block" %></td>
          <span> <i class="fa fa-angle-right"></i> </span>
      </tr>
    </tfoot>
  </table>
</div>

app/views/carts/ajhaihai.html.erb
<% provide :title, "Cart" %>
<% if !@order_line.nil? && @order_line.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @order_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if @order_lines.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_lines.each do |order_line| %>
    <%= render 'carts/cart_row', product: order_line.product, order_line: order_line, show_total: true %>
  <% end %>
<% end %>
<div class="container">
  <table id="cart" class="table table-hover table-condensed">
      <tr>
        <td><%= link_to "Continue Shopping", products_path, class: "btn btn-warning" %>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>Total Price: <%= number_to_currency current_order.subtotal %></strong></td>
        <td>
          <%= link_to "Checkout", new_order_path, class: "btn btn-success btn-block" %></td>
          <span> <i class="fa fa-angle-right"></i> </span>
      </tr>
    </tfoot>
  </table>
</div>

app/views/carts/show.html.erb
<main class="wrapper main-content detail">
	<!-- breadcrumb -->
	<div class="breadcrumbs" style="margin-top: 60px;">
		<div class="container">
			<ul class="items">
				<li class="item home">
					<a href="#" title="Go to Home Page">Home</a>
				</li>
				<li class="item cart">
					<a href="#" >Shopping Cart</a>
				</li>

			</ul>
		</div>
	</div>
	<!-- End breadcrumbs -->

	<!-- Container -->
	<div class="container">
		<!-- shop step -->
		<div class="shop-step">
			<div class="container">
				<ul class="clearfix">
					<li class="checked">
						<span class="count">01</span>
						<span class="label">Shopping cart</span>
					</li>
					<li>
						<span class="count">02</span>
						<span class="label">Check out</span>
					</li>
					<li>
						<span class="count">03</span>
						<span class="label">Order Complete</span>
					</li>
				</ul>
			</div>
			<!-- .container -->
		</div>
		<!-- .shop-step -->

		<!-- Form cart -->
		<form class="cart-form" action="#">
			<div class="table-responsive">
				<table class="table cart-table list-card-item">
					<thead>
						<tr>
							<th></th>
							<th class="product-name title">Product</th>
							<th ></th>
							<th>Price</th>
							<th>Quantity</th>
							<th>Total</th>
						</tr>
					</thead>
					<tbody>

						<%= render 'cart_shopping' %>

					</tbody>
				</table>
				<tr>
<!--    <td colspan="6" class="actions" style="padding:30px 0;">
      <div class="clearfix cart-button-group">
         <div class="coupon coupon-form col-lg-6 col-sm-6 col-xs-9">
            <label for="coupon_code">Coupon:</label>
            <div class="coupon-input-text col-lg-8 col-sm-6 col-xs-7">
               <input type="text" name="coupon_code" class="input-text " id="coupon_code" value="" placeholder="Coupon code">
            </div>
            <div class="coupon-submit-btn col-lg-4 col-sm-6 col-xs-5">
               <input type="submit" class="btn btn-primary-border" name="apply_coupon" value="Apply Coupon">
            </div>
         </div>
         <div class="update-cart-btn col-lg-6 col-sm-6 col-xs-3">
            <input type="submit" class="btn btn-primary" name="update_cart" value="Update Cart">
            <input type="hidden" id="_wpnonce" name="_wpnonce" value="a1929e2c41"><input type="hidden" name="_wp_http_referer" value="/demo/cart/">               
         </div>
      </div>
   </td> -->
</tr>
			</div>
		</form>
		<!-- end form cart -->


		<div class="cart-collaterals row">
			<div class="col-md-6">
				<div class="cal-shipping">
					<h3>Calculate Shipping</h3>
					<form action="#">
						<div class="selectbox cart-input">
							<select name="country">
								<option value="vietnam">Vietnam</option>
								<option value="us">US</option>
								<option value="uk">UK</option>
							</select>
						</div>
						<div class="selectbox cart-input">
							<select name="country">
								<option value="vietnam">State / Country</option>
							</select>
						</div>
						<div class="input-text cart-input">
							<input type="text" placeholder="Post Code / Zip">
						</div>
						<div class="input-submit">
							<input type="submit" value="Update total">
						</div>
					</form>
				</div>
				<!-- .cal-shipping -->
			</div>
			<div class="col-md-6">
				<div class="cal-shipping">
					<h3>Cart totals</h3>
					<table>
						<tr class="cart-subtotal">
							<th>Subtotals:</th>
							<td><strong><span ><%= number_to_currency current_order.subtotal %></span></strong></td>
						</tr>
						<tr class="shipping">
							<th>Shipping:</th>
							<td>Free Shipping</td>
						</tr>
						<tr class="order-total">
							<th>
								<div class="black-bg">Order Totals :</div>
							</th>
							<td>
								<div class="black-bg"><strong><span class="amount"><%= number_to_currency current_order.subtotal %></span></strong></div>
							</td>
						</tr>
					</table>
				</div>
				<!-- .cal-shipping -->
			</div>
		</div>
		<!-- .cart-collaterals -->
		<div class="cart-actions clearfix">
			<form action="#">
				<!-- <a class="button pull-right" href="checkout.html">PROCESS TO CHECK OUT</a> -->
				<%= link_to "Checkout", new_order_path, class: "button pull-right" %></td>
			</form>
		</div>
		<!-- .cart-actions -->
	</div>
	<!-- end container -->

</main>