config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home", page: "home"
  get "/static_pages/:page", to: "static_pages#show"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/orders/completed", to: "orders#completed"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/aliexpress", to: "products#aliexpress"
  resources :products
  resources :users do
    member do
      get :products
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :order_lines
  resource :cart, only: [:show]
  resources :orders
  resources :relationships
  namespace :is_admin do
    resources :products
    resources :categories, except: [:edit, :update, :destroy]
    resources :orders
  end
  namespace :shipper do
    resources :orders
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # belongs_to :state_order
  has_many :order_lines, dependent: :destroy

  before_create :set_state_order
  before_save :update_subtotal
  before_save :update_total
  before_save :update_tax

  def tax 
    subtotal * 0.1
  end

  def subtotal
    order_lines.collect { |oi| oi.valid? ? (oi.number * oi.unit_price) : 0 }.sum
  end

  private

  def set_state_order
    self.state_order_id = 1
  end

  def update_subtotal
    self.subtotal = subtotal
  end

  def update_total
    self.total = subtotal + tax
  end

  def update_tax
    self.tax = tax
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin
  
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find params[:id]
    @order_lines = @order.order_lines
  end

  def update
    @order = Order.find_by id: params[:id]
    if @order.update_attributes order_params
      flash[:success] = "Accept"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = "Can't Accept"
      redirect_to root_path
    end
  end

  private 

  def order_params
    params.require(:order).permit :state_order_id
  end
end

app/controllers/is_admin/orders_controller.rb
class IsAdmin::OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin
  
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find params[:id]
    @order_lines = @order.order_lines
  end

  def update
    @order = Order.find_by id: params[:id]
    if @order.update_attributes order_params
      flash[:success] = "Accept"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = "Can't Accept"
      redirect_to root_path
    end
  end

  private 

  def order_params
    params.require(:order).permit :state_order_id
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = current_order
  end

  def index
    @user = current_user
    @orders = @user.orders.paginate page: params[:page]
  end

  def show
    if current_order
    @order = current_user.orders.find_by id: params[:id]
    @order_lines = @order.order_lines
    end
  end

  def update
    if current_order.update_attributes order_params
      session.delete :order_id
      redirect_to orders_completed_path
    else
      redirect_to login_path
    end
  end

  def completed
  end

  private

  def order_params
    params.require(:order).permit :address, :state_order_id
  end
end

app/controllers/shipper/orders_controller.rb
class Shipper::OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :require_shipper

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find_by id: params[:id]
    @order_lines = @order.order_lines 
  end

  def update
    @order = Order.find_by id: params[:id]
    if @order.update_attributes order_params
      flash[:success] = "Success ! #{StateOrder.find(@order.state_order_id).name}!"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = "Wrong"
      redirect_to root_path
    end
  end

  private

  def order_params
    params.require(:order).permit :state_order_id
  end
end

app/views/shipper/orders/index.html.erb
<% @orders.each do |order| %>
  <% if order.state_order_id == 2 %>
    <li>
      Adress: <%= order.address %> .
      Subtotal: <%= order.subtotal %> .
      Tax:  <%= order.tax %> .
      User Name: <%= User.find(order.user_id).name %>
      Status: <%= StateOrder.find(order.state_order_id).name %>
    </li>
      <%= link_to "Detail", shipper_order_path(order) %> <br>
      <%= form_for [:shipper, order] do |f|  %>
        <%= f.hidden_field :user_id, value: order.user_id %>
        <%= f.hidden_field :order_id, value: order.id %>
        <%= f.hidden_field :state_order_id , value: '6' %>
        <%= f.submit "Take this Order" %> 
      <% end %>
  <% elsif order.state_order_id == 6 %>
  <li>
    Adress: <%= order.address %> .
    Subtotal: <%= order.subtotal %> .
    Tax:  <%= order.tax %> .
    User Name: <%= User.find(order.user_id).name %>
    Status: <%= StateOrder.find(order.state_order_id).name %>
  </li>
  <% elsif order.state_order_id == 3 %>
  <li>
    Adress: <%= order.address %> .
    Subtotal: <%= order.subtotal %> .
    Tax:  <%= order.tax %> .
    User Name: <%= User.find(order.user_id).name %>
    Status: <%= StateOrder.find(order.state_order_id).name %>
  </li>
  <%= form_for [:shipper, order] do |f|  %>
    <%= f.hidden_field :user_id, value: order.user_id %>
    <%= f.hidden_field :order_id, value: order.id %>
    <%= f.hidden_field :state_order_id , value: '4' %>
    <%= f.submit "Deliverd ! Complete" %> 
  <% end %>
  <% end %>
<% end %>