config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home", page: "home"
  get "/static_pages/:page", to: "static_pages#show"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/orders/completed", to: "orders#completed"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/aliexpress", to: "products#aliexpress"
  resources :products
  resources :users do
    member do
      get :products
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :order_lines
  resource :cart, only: [:show]
  resources :orders
  resources :relationships
  namespace :is_admin do
    resources :products
    resources :categories, except: [:edit, :update, :destroy]
    resources :orders
  end
  namespace :shipper do
    resources :orders
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin

  def index
    @categories = Category.select(:id, :parents_id,
      :name).order(:id).paginate page: params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Add Done"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by id: params[:id]
    if @category
      @books = @category.products.select(:id, :category_id, :name, :price,
        :quantity, :picture).paginate page: params[:page]
    else
      flash[:danger] = "Not Found"
      redirect_to root_path
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :parents_id
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    if logged_in?
      @order_line = current_order.order_lines.new
    end
  end

  def show
    if logged_in?
      @order_line = current_order.order_lines.new
    end
    @category = Category.find_by id: params[:id]
    if @category
      @products = @category.products.select(:id, :category_id, :name, :price,
        :quantity, :picture, :img_url).paginate page: params[:page]
    else
      flash[:danger] = "not found"
      redirect_to root_path
    end
  end
end

app/controllers/is_admin/categories_controller.rb
class IsAdmin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :require_admin

  def index
    @categories = Category.select(:id, :parents_id,
      :name).order(:id).paginate page: params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Add Done"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by id: params[:id]
    if @category
      @books = @category.products.select(:id, :category_id, :name, :price,
        :quantity, :picture).paginate page: params[:page]
    else
      flash[:danger] = "Not Found"
      redirect_to root_path
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :parents_id
  end
end

app/views/categories/index.html.erb
<% provide :title, "All Category" %>
<div class="container">
  <h1><center><%= link_to "Category", categories_path %></center></h1>
    <% @categories.each do |category| %>
    <li>
      <div class="row-fluid">
        <div class="span5">
          <div class="picture-list">
            <a><%= link_to category do %>
            <%= category.name %>
              <% end %>
            </a>
          </div>
        </div>
        <!--  -->
      </div>
    </li>
    <hr class="colorgrap">
    <% end %>
</div>

app/views/categories/show.html.erb
<div class="breadcrumbs">
   <div class="container">
      <ul class="items">
         <li class="item home">
            <a href="#" title="Go to Home Page">Home</a>
         </li>
         <li class="item category ">
            <strong><%= @category.name %></strong>
         </li>
      </ul>
   </div>
</div>
<main id="maincontent" class="page-main products-page">
   <div class="container">
      <div class="columns">                        
         <div class="column main">
            <div class="toolbar">
               <div class="sort clearfix">
                  <form action="#" class="ordering pull-left">
                     <div class="selectbox">
                        <select class="orderby" name="orderby">
                           <option value="menu_order">Default sorting</option>
                           <option value="popularity">popularity</option>
                           <option value="rating">average rating</option>
                           <option value="date">newness</option>
                           <option value="price">price: low to high</option>
                           <option value="price-desc">price: high to low</option>
                        </select>
                     </div>
                  </form>
                  <div class="style-switch pull-right">               
                     <!-- <a class="active btn-grid"  href="#" data-view="grid"><i class="fa fa-th"></i></a>
                     <a href="#" class="btn-list" data-view="list"><i class="fa fa-th-list"></i></a> -->
                  </div>
               </div>
            </div>
            <div class="product-grid clearfix" id="tabs-grid">
               <% @products.limit(9).each do |product| %>
               <div class="col-xs-12 col-sm-4">
                  <%= render "components/products/product_item", product: product%>
               </div>
               <% end %>
            </div>
         </div>
      </div>
   </div>
</main>
<script type="text/javascript">
   var products = <%= @products.to_json.html_safe -%>;

   console.log(products);
</script>